---
services:
  php:
    # https://registry.hub.docker.com/_/php
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - ./bin:/var/www/bin:delegated
      - ./config:/var/www/config:delegated
      - ./public:/var/www/public:delegated
      - ./src:/var/www/src:delegated
      - ./templates:/var/www/templates:delegated
      - ./tests:/var/www/tests:delegated
      - ./var:/var/www/var:delegated
      - ./vendor:/var/www/vendor:delegated
      - ./.env.test:/var/www/.env.test:delegated
      - ./.env:/var/www/.env:delegated
      - ./composer.json:/var/www/composer.json:delegated
      - ./composer.lock:/var/www/composer.lock:delegated
      - ./symfony.lock:/var/www/symfony.lock:delegated
      - ./phpcs.xml:/var/www/phpcs.xml:ro
      - ./phpstan.neon:/var/www/phpstan.neon:ro
  nginx:
    # https://registry.hub.docker.com/_/nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
      - '8088:80'
    volumes:
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./public:/var/www/public:ro
    environment:
      PHP_UPSTREAM_ADDR: php
    depends_on:
      - php
#  mysql:
#    # https://hub.docker.com/_/mysql
#    image: mysql:8.0.31
#    environment:
#      - MYSQL_ROOT_PASSWORD
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#      - MYSQL_DATABASE
#    ports:
#      - '3306:3306'
  node:
    # https://hub.docker.com/_/node/
    image: node:19.6-alpine3.17
    volumes:
      - ./public/:/var/www/public/:delegated
      - ./templates/:/var/www/templates/:delegated
      - ./assets:/var/www/assets:delegated
    working_dir: /var/www
